trailing_newline: error
opening_brace: error
empty_count: error
comma: error
trailing_semicolon: error
nimble_operator: error
no_extension_access_modifier: error
no_grouping_extension: error
notification_center_detachment: error
unneeded_parentheses_in_closure_argument: error
unused_closure_parameter: error
operator_usage_whitespace: error
unused_enumerated: error
vertical_parameter_alignment: error
xctfail_message: error
void_return: error
weak_delegate: error
vertical_parameter_alignment_on_call: error
operator_whitespace: error
override_in_extension: error
control_statement: error
protocol_property_accessors_order: error
quick_discouraged_call: error
quick_discouraged_focused_test: error
quick_discouraged_pending_test: error
pattern_matching_keywords: error
legacy_constant: error
line_length:
warning: 150
error: 150
return_arrow_whitespace: error
closing_brace: error
extension_access_modifier: error
todo: error
explicit_top_level_acl: error
legacy_constructor: error
empty_parameters: error
explicit_enum_raw_value: error
empty_parentheses_with_trailing_closure: error
empty_enum_arguments: error
leading_whitespace: error
array_init: error
class_delegate_protocol: error
closure_end_indentation: error
closure_parameter_position: error
closure_spacing: error
compiler_protocol_init: error
conditional_returns_on_newline:
severity: error
contains_over_first_not_nil: error
discarded_notification_center_observer: error
dynamic_inline: error
fallthrough: error
fatal_error_message: error
first_where: error
for_where: error
force_unwrapping: error
implicit_getter: error
implicit_return: error
is_disjoint: error
joined_default_parameter: error
legacy_cggeometry_functions: error
legacy_nsgeometry_functions: error
let_var_whitespace: error
literal_expression_end_indentation: error
mark: error
multiline_parameters: error
redundant_discardable_let: error
redundant_nil_coalescing: error
redundant_optional_initialization: error
redundant_string_enum_value: error
redundant_void_return: error
shorthand_operator: error
single_test_class: error
sorted_first_last: error
sorted_imports: error
strict_fileprivate: error
superfluous_disable_command: error
switch_case_alignment:
severity: error
switch_case_on_newline: error
trailing_closure: error
function_body_length:
warning: 100
error: 100
type_name:
min_length: 2
max_length: 50
identifier_name:
min_length: 3
max_length: 50
colon:
severity: error
syntactic_sugar:
severity: error
unneeded_break_in_switch:
severity: error
file_length:
warning: 800
error: 800
large_tuple:
- 3
- 3
function_parameter_count:
- 7
- 7
vertical_whitespace:
severity: error

statement_position:
severity: error

cyclomatic_complexity:
warning: 10
error: 10

reporter: "xcode"
warning_threshold: 485

excluded:
- Clean Swift/AppDelegate.swift
- Clean Swift/Helper/StringExt.swift
- Clean Swift/Helper/Service.swift
- Pods

disabled_rules:
- todo
- force_cast
- empty_enum_arguments
- force_try
- type_body_length
- redundant_string_enum_value
- valid_ibinspectable
- block_based_kvo
- trailing_whitespace
- identifier_name
- nesting
- notification_center_detachment
